### ISSUE TITLE
krecipes error adding author

### ISSUE THREAD

**Issue by ggshaman888** [eliovir/krecipes#1]
1.
a) launched the program
b) clicked a new recipe,
c) pressed the "+" sign to add the author
d) in the window that appears, in the input string put the url address
e) clicked the "+" sign to add the author
f) got the error message about exceeding the number of characters
g) clicked OK
h) pressed the icon "clear text" in the input string
i) inserted the text in the Russian language received a system crash.

2.
Expected adding the user to the database

3.
There was a collapse of the system.

---
1.
а) запустил программу
б) нажал новый рецепт,
в) нажал знак "+" для добавления автора
г) в появившемся окне, в строке ввода вставил строку с url адресом
д) нажал знак "+" для добавления автора _е) получил сообщение об ошибке о превышении количества символов
ж) нажал ОК
з) нажал иконку "clear text" в строке ввода
и) вставил текст на русском языке получил крах системы.

2.
Ожидал добавление пользователя в базу данных

3.
Произошёл крах системы.

ProblemType: Bug
DistroRelease: Ubuntu 16.04
Package: krecipes 2.1.0-2
Uname: Linux 4.14.0-041400rc7-generic x86_64
ApportVersion: 2.20.1-0ubuntu2.10
Architecture: amd64
CurrentDesktop: Unity
Date: Wed Nov 1 15:52:49 2017
InstallationDate: Installed on 2017-10-29 (3 days ago)
InstallationMedia: Ubuntu 16.04.3 LTS "Xenial Xerus" - Release amd64 (20170801)
SourcePackage: krecipes
UpgradeStatus: No upgrade log present (probably fresh install)

https://bugs.launchpad.net/ubuntu/+source/krecipes/+bug/1729269
https://www.youtube.com/edit?o=U&video_id=jkEkghjrqNk

**Comment by eliovir** [comment]
Thanks for the aknowledgment for the original bug.
NB: I do not maintain KRecipes.
